DB_NAME=financeTrackerDb
DB_USER=root
DB_PASS=Tmanna

JWT_SECRET=mySuperSecretKeyForJwtAuthentication123456
JWT_EXPIRATION=6000000

MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USER=tabc1196@gmail.com
MAIL_PASS=ixhvmsepzbjzbvoz
MAIL_FROM=mtapan2004@gmail.com


CLOUDINARY_CLOUD_NAME=dj8e7mcdf
CLOUDINARY_API_KEY=212651355247999
CLOUDINARY_API_SECRET=otmONz_JLlzgIWLCBFpBJHev2I0